openapi: 3.0.0
info:
  title: TigerTix API
  version: 1.0.0
servers:
  - url: https://api.tigertix.com
paths:
  /login:
    post:
      summary: Login
      description: Authenticates a user and returns an access token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string   

        '401':
          description: Unauthorized