openapi: 3.0.0
info:
  title: TigerTix API
  version: 1.0.0
servers:
  - url: https://api.tigertix.com
paths:
  /price:
    post:
      summary: Calculate price
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
                discountCode:
                  type: string
                  nullable: true
      responses:
        '200':
          description: Price calculated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: number
                  discountAmount:
                    type: number
                  finalPrice:
                    type: number
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error