openapi: 3.0.0
info:
  title: TigerTix API
  version: 1.0.0
servers:
  - url: https://api.tigertix.com
paths:
  /verify:
    post:
      summary: Verify a student ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                studentId:
                  type: string
                # Other relevant fields like name, institution, etc.
      responses:
        '200':
          description: Verification successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    type: boolean
                  message:
                    type: string
                  # Additional details like student name, institution, etc.
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error